<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get value - Copy</name>
   <tag></tag>
   <elementGuidId>7507e22c-08dc-4e9e-b70c-3877216abc59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttoncheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttoncheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1269c4fe-b450-4cf2-97c2-f56a5299fde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>785b1831-5417-48f9-b60a-a05ceeac4ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttoncheck</value>
      <webElementGuid>a789699c-e786-4f49-9ccf-352e89257596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-10 bg-lambda-900 border border-lambda-900 text-white rounded px-15 py-5 hover:bg-transparent hover:text-lambda-900 focus:outline-none</value>
      <webElementGuid>84e53ae2-b5cf-42e0-bca7-aec1f31c2719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get value</value>
      <webElementGuid>ecb55615-f15d-4e1c-801a-b19bf2a5c231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttoncheck&quot;)</value>
      <webElementGuid>e98e2c58-7539-4f1c-ab04-83d46b38a794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttoncheck']</value>
      <webElementGuid>a7f98902-f390-4b9a-b7f7-688e353b97f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div/div/button</value>
      <webElementGuid>5a02ab00-8d1c-4ece-aa35-816457ef5499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::button[1]</value>
      <webElementGuid>50f4f880-ed9b-423a-b42b-5f42c9d5ac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::button[1]</value>
      <webElementGuid>ad5cacea-5bb2-415c-b04e-5906b10b196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 1'])[1]/preceding::button[1]</value>
      <webElementGuid>0507d8b3-6ab9-44b7-8f0c-14e0f536ed57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 2'])[1]/preceding::button[1]</value>
      <webElementGuid>45b89a29-46aa-4c43-b56f-a38b762addd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get value']/parent::*</value>
      <webElementGuid>defeb170-b24e-41be-98ba-aad67c37b048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/button</value>
      <webElementGuid>861b1bf7-5401-4c86-b25b-69ed0dab1b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buttoncheck' and (text() = 'Get value' or . = 'Get value')]</value>
      <webElementGuid>847c07c8-1a22-44cc-8429-91b4f315e0af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
