<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get value</name>
   <tag></tag>
   <elementGuidId>6f500f1e-1c01-461c-94a0-10bfe6244877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttoncheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttoncheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0eb7d3d-b794-4cbe-9977-dcf50f1f68f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>274dd0dc-55a7-4881-baa7-a474eee6feb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttoncheck</value>
      <webElementGuid>99b597e9-b515-4af9-a2dc-f222e19160d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-10 bg-lambda-900 border border-lambda-900 text-white rounded px-15 py-5 hover:bg-transparent hover:text-lambda-900 focus:outline-none</value>
      <webElementGuid>8d7eaabe-59c1-40dd-b3de-c0d136c9b719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get value</value>
      <webElementGuid>96e0eec1-4d89-46ed-90af-98603cb0332f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttoncheck&quot;)</value>
      <webElementGuid>12a238bf-0bfc-42c0-81e8-96ebc9c5938f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttoncheck']</value>
      <webElementGuid>0701b7b3-5bf2-4544-9829-a9899cf9c4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div/div/button</value>
      <webElementGuid>f0bff70e-6e15-456e-8f22-eee9b25ed297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::button[1]</value>
      <webElementGuid>2b99e27e-10ac-4f56-8b34-7b316e2c587a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::button[1]</value>
      <webElementGuid>2da78bf7-cbd7-4327-bebd-3652155bd49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 1'])[1]/preceding::button[1]</value>
      <webElementGuid>dfd54794-1159-46e2-a6d6-43ff347ee982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 2'])[1]/preceding::button[1]</value>
      <webElementGuid>1bbf2123-becf-4bb6-a91a-73b008e67f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get value']/parent::*</value>
      <webElementGuid>2664d2b5-0112-4ea7-ac60-104757197d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/button</value>
      <webElementGuid>c9817b3f-8cf8-4a80-9a20-607c98fdcf7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buttoncheck' and (text() = 'Get value' or . = 'Get value')]</value>
      <webElementGuid>8f359e15-c890-4a0d-8a63-4e697e924b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
